// Image asset names
export const IMAGE_ASSETS = [
    'floors/dirt/dirt.png',
    'rock.png',
    'floors/dirt/dirt_north.png',
    'floors/dirt/dirt_corner.png',
    'floors/dirt/dirt_tunnel.png',
    'floors/dirt/dirt_corner2.png',
    'shrubbery.png',
    'bush.png',
    'floors/dirt/dircle.png',
    'doodads/club.png',
    'doodads/table.png',
    'items/water.png',
    'doodads/shack.png',
    'protag/Special2.png',
    'doodads/cistern.png',
    'protag/whack.png',
    'protag/dead.png',
    'fauna/lizardy.png',
    'fauna/lizardo.png',
    'fauna/lizardeaux.png',
    'fauna/lizord.png',
    'fauna/lazerd.png',
    'items/axe.png',
    'items/hammer.png',
    'items/spear.png',
    'items/bomb.png',
    'items/heart.png',
    'items/note.png',
    'items/book.png',
    'items/bow.png',
    'doodads/stairdown.png',
    // Use the actual stairup filename present in the repo; TextureLoader will accept both names
    'doodads/stairup.png',
    'items/shovel.png',
    'items/points.png',
    'items/chest.png',
    'doodads/well.png',
    'doodads/hole.png',
    'doodads/deadtree.png',
    'doodads/pitfall.png',
    'fauna/penne.png',
    'fauna/squig.png',
    'fauna/nib.png',
    'fauna/rune.png',
    'fauna/crayn.png',
    'fauna/felt.png',
    'fauna/forge.png',
    'fauna/mark.png',
    'fauna/gouge.png',
    'fauna/gougeface.png',
    'fauna/axolotl.png',
    'fauna/forgeface.png',
    'fauna/axolotlface.png',
    'fauna/zard.png',
    'floors/frontier/desert.png',
    'flora/succulent.png',
    'flora/stump.png',
    'flora/blocklily.png',
    'flora/boulder.png',
    'sign.png',
    'items/horse.png',
    'protag/default.png',
    'protag/faceset.png',
    'items/arrow.png',
    'floors/interior/housetile.png',
    'floors/interior/house_wall_corner.png',
    'floors/interior/house_wall_side.png',
    'floors/interior/house_wall_open.png',
    'ui/arrow.png',
    'fx/smoke/smoke_frame_1.png',
    'fx/smoke/smoke_frame_2.png',
    'fx/smoke/smoke_frame_3.png',
    'fx/smoke/smoke_frame_4.png',
    'fx/smoke/smoke_frame_5.png',
    'fx/smoke/smoke_frame_6.png',
    'fx/splode/splode_1.png',
    'fx/splode/splode_2.png',
    'fx/splode/splode_3.png',
    'fx/splode/splode_4.png',
    'fx/splode/splode_5.png',
    'fx/splode/splode_6.png',
    'fx/splode/splode_7.png',
    'fx/splode/splode_8.png'
    , 'fx/fog.png'
];

// Food image assets
export const FOOD_ASSETS = [
    'food/meat/beaf.png',
    'food/veg/nut.png',
    'food/aguamelin.png'
];

export const TOTAL_IMAGES = IMAGE_ASSETS.length + FOOD_ASSETS.length;
