/**
 * Type declarations for virtual modules generated by Vite plugins
 */

declare module 'virtual:npc-list' {
    export const npcList: string[];
    export const npcPaths: Array<{ id: string; path: string }>;
}

/**
 * Global window augmentation for overlay animations
 */
declare global {
    interface Window {
        animateOverlayCurl: (overlayElement: HTMLElement | null) => Promise<void>;
    }
}

export {};
