// Auto-discovered image assets
// This file now imports from the virtual asset manifest generated at build time
// The manifest is automatically generated by scanning the assets directory

import { IMAGE_ASSETS as DISCOVERED_IMAGE_ASSETS, ASSET_CATEGORIES } from 'virtual:asset-manifest';

// Export the discovered image assets
export const IMAGE_ASSETS = DISCOVERED_IMAGE_ASSETS;

// Food assets are now automatically discovered from items/consumables/
export const FOOD_ASSETS = ASSET_CATEGORIES.items
    .filter(path => path.startsWith('items/consumables/'))
    .filter(path => !path.includes('water.png')); // Exclude water as it's not food

export const TOTAL_IMAGES = IMAGE_ASSETS.length + FOOD_ASSETS.length;

// Re-export asset categories for easy access
export { ASSET_CATEGORIES } from 'virtual:asset-manifest';
