// Image asset names
export const IMAGE_ASSETS = [
    // Floor textures
    'environment/floors/bones.png',
    'environment/floors/clouds.png',
    'environment/floors/crackedseaice.png',
    'environment/floors/crag.png',
    'environment/floors/desert.png',
    'environment/floors/dirt.png',
    'environment/floors/dirtpatch.png',
    'environment/floors/grass.png',
    'environment/floors/gravel.png',
    'environment/floors/housetile.png',
    'environment/floors/mulch.png',
    'environment/floors/seaice.png',
    'environment/floors/underbrush.png',
    'environment/floors/aqua.png',
    // Wall textures
    'environment/walls/rockwall.png',
    'environment/walls/clubwall.png',
    'environment/walls/clubwall1.png',
    'environment/walls/clubwall2.png',
    'environment/walls/clubwall4.png',
    'environment/walls/clubwall5.png',
    'environment/walls/clubwall6.png',
    'environment/walls/90s.png',
    'environment/walls/astrocrag.png',
    'environment/trim/bordertrim.png',
    'environment/walls/chargedwall.png',
    'environment/walls/cobble.png',
    'environment/walls/coralwall.png',
    'environment/walls/cube.png',
    'environment/walls/deco.png',
    'environment/walls/fortwall.png',
    'environment/walls/heartstone.png',
    'environment/walls/lavawall.png',
    'environment/walls/zydeco.png',
    'environment/obstacles/rock.png',
    'environment/obstacles/shrubbery.png',
    'environment/walls/bush.png',
    'environment/doodads/club.png',
    'environment/doodads/table.png',
    'items/consumables/water.png',
    'environment/doodads/shack.png',
    'characters/player/Special2.png',
    'environment/doodads/cistern.png',
    'characters/player/whack.png',
    'characters/player/dead.png',
    'characters/enemies/lizardy.png',
    'characters/enemies/lizardo.png',
    'characters/enemies/lizardeaux.png',
    'characters/enemies/lizord.png',
    'characters/enemies/lazerd.png',
    'items/equipment/axe.png',
    'items/equipment/hammer.png',
    'items/equipment/spear.png',
    'items/misc/bomb.png',
    'items/misc/heart.png',
    'items/misc/note.png',
    'items/misc/book.png',
    'items/equipment/bow.png',
    'environment/doodads/stairdown.png',
    // Use the actual stairup filename present in the repo; TextureLoader will accept both names
    'environment/doodads/stairup.png',
    'items/equipment/shovel.png',
    'items/misc/points.png',
    'items/misc/chest.png',
    'environment/doodads/well.png',
    'environment/doodads/hole.png',
    'environment/doodads/deadtree.png',
    'environment/doodads/pitfall.png',
    'characters/npcs/penne.png',
    'characters/npcs/squig.png',
    'characters/npcs/nib.png',
    'characters/npcs/rune.png',
    'characters/npcs/crayn.png',
    'characters/npcs/felt.png',
    'characters/npcs/forge.png',
    'characters/npcs/mark.png',
    'characters/npcs/gouge.png',
    'characters/npcs/portraits/gougeface.png',
    'characters/npcs/axolotl.png',
    'characters/npcs/portraits/forgeface.png',
    'characters/npcs/portraits/axolotlface.png',
    'characters/npcs/portraits/craynface.png',
    'characters/npcs/portraits/feltface.png',
    'characters/npcs/portraits/markface.png',
    'characters/npcs/portraits/nibface.png',
    'characters/npcs/portraits/penneface.png',
    'characters/npcs/portraits/runeface.png',
    'characters/npcs/portraits/squigface.png',
    'characters/enemies/zard.png',
    'environment/floors/desert.png',
    'environment/walls/succulent.png',
    'environment/walls/stump.png',
    'environment/walls/blocklily.png',
    'environment/walls/boulder.png',
    'environment/doodads/sign.png',
    'items/misc/horse.png',
    'characters/player/default.png',
    'characters/player/faceset.png',
    'items/misc/arrow.png',
    'environment/floors/housetile.png',
    'ui/arrow.png',
    'environment/effects/smoke_frame_1.png',
    'environment/effects/smoke_frame_2.png',
    'environment/effects/smoke_frame_3.png',
    'environment/effects/smoke_frame_4.png',
    'environment/effects/smoke_frame_5.png',
    'environment/effects/smoke_frame_6.png',
    'environment/effects/splode_1.png',
    'environment/effects/splode_2.png',
    'environment/effects/splode_3.png',
    'environment/effects/splode_4.png',
    'environment/effects/splode_5.png',
    'environment/effects/splode_6.png',
    'environment/effects/splode_7.png',
    'environment/effects/splode_8.png',
    'environment/effects/fog.png'
] as const;

export type ImageAsset = typeof IMAGE_ASSETS[number];

// Food image assets
export const FOOD_ASSETS = [
    'items/consumables/beaf.png',
    'items/consumables/nut.png',
    'items/consumables/aguamelin.png'
] as const;

export type FoodAsset = typeof FOOD_ASSETS[number];

export const TOTAL_IMAGES = IMAGE_ASSETS.length + FOOD_ASSETS.length;
