// Auto-generated by tools/generate-editor-assets.js
// DO NOT EDIT MANUALLY

// Wall assets discovered from environment/walls/
export const DISCOVERED_WALLS = [
  "environment/walls/90s.png",
  "environment/walls/astrocrag.png",
  "environment/walls/blocklily.png",
  "environment/walls/boulder.png",
  "environment/walls/bush.png",
  "environment/walls/chargedwall.png",
  "environment/walls/clubwall.png",
  "environment/walls/clubwall1.png",
  "environment/walls/clubwall2.png",
  "environment/walls/clubwall4.png",
  "environment/walls/clubwall5.png",
  "environment/walls/clubwall6.png",
  "environment/walls/cobble.png",
  "environment/walls/coralwall.png",
  "environment/doodads/cube.png",
  "environment/walls/deco.png",
  "environment/walls/fortwall.png",
  "environment/walls/heartstone.png",
  "environment/walls/lavawall.png",
  "environment/walls/rockwall.png",
  "environment/walls/stump.png",
  "environment/walls/succulent.png",
  "environment/walls/zydeco.png"
];

// Floor assets discovered from environment/floors/
export const DISCOVERED_FLOORS = [
  "environment/floors/bones.png",
  "environment/floors/clouds.png",
  "environment/floors/crackedseaice.png",
  "environment/floors/crag.png",
  "environment/floors/desert.png",
  "environment/floors/dirt.png",
  "environment/floors/dirtpatch.png",
  "environment/floors/grass.png",
  "environment/floors/gravel.png",
  "environment/floors/housetile.png",
  "environment/floors/mulch.png",
  "environment/floors/seaice.png",
  "environment/floors/underbrush.png",
  "environment/floors/aqua.png"
];

// Trim assets discovered from environment/trim/
export const DISCOVERED_TRIM = [
  "environment/trim/bordertrim.png"
];

// Obstacle assets discovered from environment/obstacles/
export const DISCOVERED_OBSTACLES = [
  "environment/obstacles/rock.png",
  "environment/obstacles/shrubbery.png"
];

// Generate tile assets mapping
export function generateTileAssets() {
    const tileAssets = {};

    // Add walls
    DISCOVERED_WALLS.forEach(path => {
        const key = 'walls/' + path.split('/').pop().replace('.png', '');
        tileAssets[key] = '../assets/' + path;
    });

    // Add floors
    DISCOVERED_FLOORS.forEach(path => {
        const key = 'floors/' + path.split('/').pop().replace('.png', '');
        tileAssets[key] = '../assets/' + path;
    });

    // Add trim
    DISCOVERED_TRIM.forEach(path => {
        const key = 'trim/' + path.split('/').pop().replace('.png', '');
        tileAssets[key] = '../assets/' + path;
    });

    // Add obstacles
    DISCOVERED_OBSTACLES.forEach(path => {
        const key = 'obstacles/' + path.split('/').pop().replace('.png', '');
        tileAssets[key] = '../assets/' + path;
    });

    return tileAssets;
}

// Generate palette arrays
export function generateWallPalette() {
    return DISCOVERED_WALLS.map(path =>
        'walls/' + path.split('/').pop().replace('.png', '')
    ).concat([null]);
}

export function generateFloorPalette() {
    return DISCOVERED_FLOORS.map(path =>
        'floors/' + path.split('/').pop().replace('.png', '')
    ).concat([null]);
}
